@ECHO OFF
REM Generated by Nexteer PDX-BAT Generation Tool v 3.19.x
REM Nexteer Automotive
set mergedir=%cd%
IF NOT EXIST "%mergedir%\pdx_temp\" (mkdir pdx_temp)
IF NOT EXIST "%mergedir%\tal_temp\" (mkdir tal_temp)
IF NOT EXIST "%mergedir%\nexteer_temp\" (mkdir nexteer_temp)
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\SWE3 Definitions 11NOV2016.txt" "C:\Users\rz4prm\Desktop\19-07-300_240200\SWE3 Definitions 11NOV2016.txt"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\SWE3 Definitions 11NOV2016.txt" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp\SWE3 Definitions 11NOV2016.txt"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\" "C:\Users\rz4prm\Desktop\19-07-300_240200\"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp\"
IF NOT EXIST "%mergedir%\SweGen_768_OBD_3_SWE1.cfg" (copy "C:\PDXGen_Resources\SweGen_768_OBD_3_SWE1.cfg" "%mergedir%")
IF NOT EXIST "%mergedir%\SweGen_768_OBD_3_SWE2.cfg" (copy "C:\PDXGen_Resources\SweGen_768_OBD_3_SWE2.cfg" "%mergedir%")
IF NOT EXIST "%mergedir%\SweGen_768_OBD_3_SWE3.cfg" (copy "C:\PDXGen_Resources\SweGen_768_OBD_3_SWE3.cfg" "%mergedir%")
copy "C:\Users\rz4prm\Desktop\19-07-300_240200\MERGED SOFTWARE\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out" "C:\PDXGen_Resources\"
PATH="C:\Windows\System32\"
cd /d "C:\PDXGen_Resources\"
PATH="C:\PDXGen_Resources\"
CCT -MMFTCTR_03.02.00.hex BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out -oBMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out -v2
DEL BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out
cd /d "C:\PDXGen_Resources\"
PATH="C:\PDXGen_Resources\"
nowecc -i BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out -f021 16M_ADD -r4 -a
hex470 -i -o Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex -map Flashmap.hex.map -datawidth 8 -memwidth 8 -romwidth 8 -i BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out
PATH="C:\Windows\System32\"
copy BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out "%mergedir%\"
copy Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex "%mergedir%\"
DEL Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex
DEL BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out
DEL Flashmap.Hex.Map
IF EXIST nowECC.Log (DEL nowECC.Log)
cd /d %mergedir%
SET PROJ_PATH="%cd%"
PATH="C:\PDXGen_Resources\"
SWE-Generator.exe -mode swegen -config SweGen_768_OBD_3_SWE1.cfg -par Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex -par SWFL_0000508b_009_009_013 -gui off -log SWElogfile_SWFL_0000508b_009_009_013.txt
cd /d %mergedir%
copy "C:\Users\rz4prm\Desktop\19-07-300_240200\MERGED SOFTWARE\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out" "C:\PDXGen_Resources\"
PATH="C:\Windows\System32\"
cd /d "C:\PDXGen_Resources\"
PATH="C:\PDXGen_Resources\"
CCT -MMFTCTR_03.02.00.hex BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out -oBMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out -v2
DEL BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out
cd /d "C:\PDXGen_Resources\"
PATH="C:\PDXGen_Resources\"
nowecc -i BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out -f021 16M_ADD -r4 -a
hex470 -i -o Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex -map Flashmap.hex.map -datawidth 8 -memwidth 8 -romwidth 8 -i BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out
PATH="C:\Windows\System32\"
copy BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out "%mergedir%\"
copy Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex "%mergedir%\"
DEL Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex
DEL BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out
DEL Flashmap.Hex.Map
IF EXIST nowECC.Log (DEL nowECC.Log)
cd /d %mergedir%
SET PROJ_PATH="%cd%"
PATH="C:\PDXGen_Resources\"
SWE-Generator.exe -mode swegen -config SweGen_768_OBD_3_SWE2.cfg -par Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex -par SWFL_0000508c_160_013_013 -gui off -log SWElogfile_SWFL_0000508c_160_013_013.txt
cd /d %mergedir%
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\MERGED SOFTWARE\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out"
IF NOT EXIST "%mergedir%\swfl_0000508d_030_021_012.bsw" (copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\swfl_0000508d_030_021_012.bsw" "%mergedir%")
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\swfl_0000508d_030_021_012.bsw" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp\swfl_0000508d_030_021_012.bsw"
IF NOT EXIST "%mergedir%\swfl_0000508d_032_021_012.bsw" (copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\swfl_0000508d_032_021_012.bsw" "%mergedir%")
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\swfl_0000508d_032_021_012.bsw" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp\swfl_0000508d_032_021_012.bsw"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\MERGED SOFTWARE\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\swfl_0000508d_030_021_012.bsw" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp\swfl_0000508d_030_021_012.bsw"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\swfl_0000508d_032_021_012.bsw" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp\swfl_0000508d_032_021_012.bsw"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\MERGED SOFTWARE\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged.out"
IF NOT EXIST "%mergedir%\swfl_0000508d_031_021_012.bsw" (copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\swfl_0000508d_031_021_012.bsw" "%mergedir%")
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\swfl_0000508d_031_021_012.bsw" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp\swfl_0000508d_031_021_012.bsw"
IF NOT EXIST "%mergedir%\swfl_0000508d_033_021_012.bsw" (copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\swfl_0000508d_033_021_012.bsw" "%mergedir%")
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\swfl_0000508d_033_021_012.bsw" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp\swfl_0000508d_033_021_012.bsw"
Pause
