@ECHO OFF
REM Generated by Nexteer PDX-BAT Generation Tool v 3.19.x
REM Nexteer Automotive
set mergedir=%cd%
IF NOT EXIST btld_0000511c_006_001_000.bsw (copy "C:\PDXGen_Resources\btld_0000511c_006_001_000.bsw" "C:\Users\rz4prm\Desktop\19-07-300_240200\" )
IF NOT EXIST sweseq_0000511c.xml.006_001_000 (copy "C:\PDXGen_Resources\sweseq_0000511c.xml.006_001_000" "C:\Users\rz4prm\Desktop\19-07-300_240200\" )
IF NOT EXIST cafd_0000123c.caf.002_027_000 (copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\cafd_0000123c.caf.002_027_000" "C:\Users\rz4prm\Desktop\19-07-300_240200\" )
cd /d %mergedir%
SET PROJ_PATH="%cd%"
PATH="C:\PDXGen_Resources\"
cd /d %mergedir%
IF NOT EXIST SWFL_0000508b_009_009_013_signed.xml (
echo
echo Error - signed XML not found.  Operation will be terminated.
echo file: SWFL_0000508b_009_009_013_signed.xml
Pause
Exit
)
SWE-Generator.exe -mode hash -hashlist SWFL_0000508b_009_009_013_signed.xml -gui on
SWE-Generator.exe -mode compress -compressmode compressconvert -compressinput SWFL_0000508b_009_009_013.msr -compressoutput SWFL_0000508b_009_009_013.bsw -efficiency 50 -log logfile.log -gui off -forcecompression off
PATH="C:\Windows\System32\"
Copy "%mergedir%\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out" "%mergedir%\nexteer_temp"
Copy "%mergedir%\SWFL_0000508b_009_009_013.bsw" "%mergedir%\nexteer_temp"
Copy "%mergedir%\Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex" "%mergedir%\nexteer_temp"
Copy "%mergedir%\SWFL_0000508b_009_009_013.s19" "%mergedir%\nexteer_temp"
Copy "%mergedir%\SWFL_0000508b_009_009_013.msr" "%mergedir%\nexteer_temp"
Copy "%mergedir%\SWFL_0000508b_009_009_013_signed.xml" "%mergedir%\nexteer_temp"
cd /d %mergedir%
SET PROJ_PATH="%cd%"
PATH="C:\PDXGen_Resources\"
cd /d %mergedir%
IF NOT EXIST SWFL_0000508c_160_013_013_signed.xml (
echo
echo Error - signed XML not found.  Operation will be terminated.
echo file: SWFL_0000508c_160_013_013_signed.xml
Pause
Exit
)
SWE-Generator.exe -mode hash -hashlist SWFL_0000508c_160_013_013_signed.xml -gui on
SWE-Generator.exe -mode compress -compressmode compressconvert -compressinput SWFL_0000508c_160_013_013.msr -compressoutput SWFL_0000508c_160_013_013.bsw -efficiency 50 -log logfile.log -gui off -forcecompression off
PATH="C:\Windows\System32\"
Copy "%mergedir%\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out" "%mergedir%\nexteer_temp"
Copy "%mergedir%\SWFL_0000508c_160_013_013.bsw" "%mergedir%\nexteer_temp"
Copy "%mergedir%\Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex" "%mergedir%\nexteer_temp"
Copy "%mergedir%\SWFL_0000508c_160_013_013.s19" "%mergedir%\nexteer_temp"
Copy "%mergedir%\SWFL_0000508c_160_013_013.msr" "%mergedir%\nexteer_temp"
Copy "%mergedir%\SWFL_0000508c_160_013_013_signed.xml" "%mergedir%\nexteer_temp"
PATH="C:\Windows\System32\"
Copy "%mergedir%\swfl_0000508d_030_021_012.bsw" "%mergedir%\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_K_F40.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\tal_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_K_F40.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
PATH="C:\Windows\System32\"
Copy "%mergedir%\swfl_0000508d_032_021_012.bsw" "%mergedir%\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_K_F44.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\tal_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_K_F44.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_M_F40.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\tal_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_M_F40.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_M_F44.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\tal_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_M_F44.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
PATH="C:\Windows\System32\"
Copy "%mergedir%\swfl_0000508d_031_021_012.bsw" "%mergedir%\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_Q_F40_SPORT.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\tal_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_Q_F40_SPORT.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
PATH="C:\Windows\System32\"
Copy "%mergedir%\swfl_0000508d_033_021_012.bsw" "%mergedir%\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_Q_F44_SPORT.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\tal_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\TAL_EPS__NEX01__F40.030_004_013__Var_Q_F44_SPORT.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
cd /d C:\EC-Apps\ESG\E-Sys
call E-Sys.bat -pdxcontainer "C:\Users\rz4prm\Desktop\19-07-300_240200\EPS__NEX01__F40.030_004_013_def.xml" -out "C:\Users\rz4prm\Desktop\19-07-300_240200\EPS__NEX01__F40.030_004_013.pdx"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\sweseq_0000511c.xml.006_001_000" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\cafd_0000123c.caf.002_027_000" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\btld_0000511c_006_001_000.bsw" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\EPS__NEX01__F40.030_004_013.pdx" "C:\Users\rz4prm\Desktop\19-07-300_240200\pdx_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\EPS__NEX01__F40.030_004_013.pdx" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\EPS__NEX01__F40.030_004_013_def.xml" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\BMW_Rel_UKL_19_07_I300_160_A7.scp" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\_runfirst_PDX_19_07_300_PRE_240200_0.bat" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\_runsecond_PDX_19_07_300_PRE_240200_0.bat" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\PDXgeneration v03p19p03_1907300_240200.xlsm" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
Copy "C:\Users\rz4prm\Desktop\19-07-300_240200\INPUTS\PT01_template.003_000_194.pdx" "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
PATH="C:\Windows\System32\"
cd "C:\PDXGen_Resources\"
CScript zip_variable.vbs "C:\Users\rz4prm\Desktop\19-07-300_240200\pdx_temp" "C:\Users\rz4prm\Desktop\19-07-300_240200\_PDX_PDX_19_07_300_PRE_240200_0.zip" 45000
CScript zip_variable.vbs "C:\Users\rz4prm\Desktop\19-07-300_240200\tal_temp" "C:\Users\rz4prm\Desktop\19-07-300_240200\_TAL_PDX_19_07_300_PRE_240200_0.zip" 45000
CScript zip_variable.vbs "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp" "C:\Users\rz4prm\Desktop\19-07-300_240200\_AllFiles_PDX_19_07_300_PRE_240200_0.zip" 120000
cd "C:\Users\rz4prm\Desktop\19-07-300_240200\"
ECHO Please confirm that zip files were correctly generated before deleting files.
ECHO Close this window to terminate script, or press any key to continue deleting files
Pause
DEL /Q "C:\Users\rz4prm\Desktop\19-07-300_240200\pdx_temp"
DEL /Q "C:\Users\rz4prm\Desktop\19-07-300_240200\tal_temp"
DEL /Q "C:\Users\rz4prm\Desktop\19-07-300_240200\nexteer_temp"
DEL /Q "C:\Users\rz4prm\Desktop\19-07-300_240200\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out"
DEL /Q "C:\Users\rz4prm\Desktop\19-07-300_240200\Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex"
DEL /Q "C:\Users\rz4prm\Desktop\19-07-300_240200\BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.out"
DEL /Q "C:\Users\rz4prm\Desktop\19-07-300_240200\Flash_BMW_Rel_UKL_19_07_I300_160_A7_240200_merged_mergetc.hex"
rmdir pdx_temp
rmdir tal_temp
rmdir nexteer_temp
Pause
